### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by BaxAndrei** [BrightSkyz/ModuleRepo#3]
Fresh install, click install /w ModuleRepo give me: https://i28.servimg.com/u/f28/17/31/96/85/screen11.png

**Comment by BrightSkyz** [comment]
Sorry for late reply, wasn't expecting anyone to actually use this. Could you send me the error you receive? (Check web server logs and send me it.)

**Comment by BaxAndrei** [comment]
error_log it`s empty :( no error_log was generated.

**Comment by BrightSkyz** [comment]
They were using the latest dev code for NamelessMC v2 (which has some incompatible things) so it wouldn't work. Current latest version is for 2.0.0-pr4.
